### ISSUE TITLE
Feature Request: add "statement-with-params"

### ISSUE THREAD

**Issue by default-kramer** [racket/db#12]
The `statement?` contract allows 5 different things as described in section 3.1 of the docs. I would like to add a 6th idea, a "statement with parameters" that represents a statement plus a list of values for the parameters.

I think this is the best way to explain how I think it would work:
```
(define swp
  (statement-with-params sql-string (list p1 p2)))

; The following two would be equivalent
(query-exec conn swp)
(query-exec conn sql-string p1 p2)

; The following should probably be be an error:
(query-exec conn swp foo)
```

Why do I want this? In my project "plisqin" I might write a query like
```
(define plisqin-query
  {from x "X"
    {where x.Foo = {param bar}}})
```
This query object can implement `prop:statement` and return a statement-with-params. Then I can write `(query-exec conn plisiqn-query)`

If this seems reasonable I'd be willing to work on it.

**Comment by rmculpepper** [comment]
You can create a `statement-with-params` struct type that implements `prop:statement` with a function that calls `prepare` and `bind-prepared-statement` to produce one of the base types of statement. The `sql` library's `sql-statement` struct works roughly the same way; see https://github.com/rmculpepper/sql/blob/792895fae759c6ef60aff054c1f707bb4f15407a/private/syntax.rkt#L148 (but use the function interface instead of direct method calls... I may have just noticed a bug in my use of the `prepare` method).

**Comment by default-kramer** [comment]
I see, that should work, thanks.

I thought that `prepare` might cause an extra round trip to the DB (can it?), in which case I would want to be able to avoid using `prepare` for certain queries.

**Comment by default-kramer** [comment]
I just grabbed Wireshark and ran a test. For Postgres, `prepare` does force an immediate round trip to the DB. But I also noticed that `query-rows` does two round trips. (I'm guessing it is implemented as prepare + execute.) Meaning the "prepare + execute" pattern is almost identical to the "execute" pattern.

So I think my concern is valid, but it's also a very premature optimization at this point.

(I am much more familiar with SQL Server these days, and in SQL Server preparing statements has become pretty useless. All execution plans are considered equally for caching, regardless of whether they are prepared or ad-hoc statements. There is a good explanation here: https://dba.stackexchange.com/questions/129659/what-is-the-sense-and-benefit-of-using-sqlcommand-prepare)

**Comment by rmculpepper** [comment]
Yes, the db library always prepares a statement first if there are parameters. The main reason is to get the number (and sometimes the types) of the parameters from the database backend, so mismatches can be caught on the Racket side instead of by the backend. That makes the errors more consistent, but it also affects the semantics; on PostgreSQL, for example, any error in the backend invalidates the current transaction.

**Comment by default-kramer** [comment]
Makes sense, thanks for the explanation.
